name: Node.js CI

on:
  push:
    branches:
      - prod
      - stage
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.0.0'
          npm-version: '7.0.0' 

      - name: Install dependencies
        run: npm install

      - name: Linter
        run: npm run lint

      - name: Formatter
        run: npm run prettier

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build